### ISSUE TITLE
Error Invalid user name app in section 'program:uwsgi' during install on Centos 7

### ISSUE THREAD

**Issue by taryep** [chembience/chembience#10]
Hello, thank you for your awesome work !

I recently tried to install and start this project following the documentation on github. 
At the step starting Django (`./up` command), I get an error: 
```
chembience-django | Error: Invalid user name app in section 'program:uwsgi' (file: '/home/nginx/supervisord.conf')
chembience-django | For help, use /usr/bin/supervisord -h
chembience-django exited with code 2
```
You can find all the details on [the secret gist](https://gist.github.com/taryep/fd9da3f4c2e9875c2ae7db68467e05b1)

System:
Linux Centos 7
Versions: 
Docker version 18.09.3, build 774a1f4
docker-compose version 1.18.0, build 8dd22a9

I hope you will be able to help me :blush: !

**Comment by markussitzmann** [comment]
Hi taryep,

thanks for your report. However, please don't run any of these scripts as root, that won't work. You must initialize Chembience this as a regular user with a regular group id (both UID and GID must be something !=0, usually >= 1000)

I hope that helps,
Markus

**Comment by taryep** [comment]
Hi Markus !
Thanks a lot for your answer. 
I had never configured Docker to run without sudo, so I badly thought that I had to launch your project as root. I followed [this tutorial](https://docs.docker.com/install/linux/linux-postinstall/) to configure it.
Then, It worked pretty well ! :+1: 
Taryep

**Comment by markussitzmann** [comment]
Well, I had put quite a bit of an effort into the content of the Chembience containers running not as root user (as far it was reasonable possible) but the user who started the container (for better security). So your root attempt undermined that kind of ;-). Anyway, your issue will be part of the Chembience history as the first user issue I successfully resolved :-)

**Comment by taryep** [comment]
Haha ! Congrats on resolving this first issue :smile: ! 
I have another one, I don’t l know if I should open a git issue, or if you will tell me here how to resolve it. 
The Django code I’m trying to deploy using Chembience has been developed in version 1.11 LTS. 
I tried to change the requirements file to impose to install this version (1.11), but it seems that Django 2 is still installed instead of Django 1.11. 
Would you be insterested into seeing the logs in a new issue ? 
The solution I found for the moment is to move my Django apps to the last version to match with Chembience requirements. Even if I didn’t realized those changes yet. 
I hope you will also be able to help me on this ! 
Taryep

**Comment by markussitzmann** [comment]
You can do that (I am currently preparing web pages to describe things like that but that is still work in progress).

Try this:
1. Go to ~/chembient/django (or where your Django app resides)
2. Adjust your requirements.txt files as you need it
3. Go into chembience.django.env
and set DJANGO_APP_VERSION to some personalized string or use a personalized tag, i.e. change
  
`DJANGO_APP_HOME=@DJANGO_APP_HOME`

to e.g.

`DJANGO_APP_HOME=**django:my-personal-image**`

4. Run ./build
5 Run ./up

The image should fullfill your requirements (since my urls.py is adjusted to Django 2.0 you have to replace it with yours, too, otherwise it might see a Django error message).

The only caveat: if you want to run the image or service somewhere else (another host), it is your responsibility to make the image "django:my-personal-image" available there (vs. if you would still use the original, this could be delivered anywhere from dockerhub)
