### ISSUE TITLE
Django 3

### ISSUE THREAD

**Issue by roukydesbois** [chembience/chembience#14]
Hello!
I'm starting to use chembience for some of my personal projects and I really like the approach and ease of use.
Is there any specific reason for not having Django 3 shipped in Chembience?
Thanks!

**Comment by markussitzmann** [comment]
Hello roukydesbois,

no, there are no particular reasons except for the next version of Chembience is heavily delayed because I didn't find time to do it (and back then I still had a dependency on Django 2.x).However, you can build the images quite easily yourself. If you have checked it out, go into context/build/django and edit requirements.txt. Then go into the root directory and run ./build - it should rebuild the Django image then. Please tell me, if it worked for you. I also hope to deliver newer images soon based on Django 3.

**Comment by roukydesbois** [comment]
You rock, it worked, thanks!
